# Default values for mcp-mssql subchart

# Namespace (inherited from parent)
namespace: ""

# MCP MSSQL Configuration
backend:
  name: "mcp-mssql-backend"
  targetName: "mcp-mssql-target"
  host: "mcp-mssql-service.{{ .Values.namespace }}.svc.cluster.local"
  protocol: "StreamableHTTP"
deployment:
  name: "mcp-mssql"
  replicas: 1
  image:
    repository: "kamalberrybytes/mssql-mcp"
    tag: "v1"
    pullPolicy: "Always"
  env:
    mssqlServer: ""
    mssqlDatabase: ""
    mssqlPort: ""
    mssqlUser: ""
    mssqlPassword: ""
service:
  name: "mcp-mssql-service"
  port: 8000
  targetPort: 8000
  appProtocol: "kgateway.dev/mcp"
httpRoute:
  name: "mcp-mssql"