apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "mcp-hubspot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mcp-hubspot.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      appProtocol: {{ .Values.service.appProtocol }}