apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  mcp:
    targets:
      - name: {{ .Values.backend.targetName }}
        static:
          host: {{ tpl .Values.backend.host . | quote }}
          port: {{ .Values.service.port }}
          protocol: {{ .Values.backend.protocol }}