apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  parentRefs:
    - name: agentgateway-proxy
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ui
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}