apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ui.secret.name" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AZURE_CLIENT_SECRET: {{ include "ui.azureClientSecret" . }}
  SECRET_KEY: {{ include "ui.secretKey" . }}